@echo off

set CIRCUITPY_FLASH_PATH=D:
rem set CIRCUITPY_IMAGE_PATH=.\lumensaliscplib\lib
set CIRCUITPY_IMAGE_PATH=.\lumensaliscplib\out\lib
set CIRCUITPY_DEPENDNCIES_PATH=.\CircuitPyDependencies
set ROBOCOPY_NONVERBOSE= /NJH /NJS /NDL
set ROBOCOPY_ARGS=/E /XD .git /XD __pycache__ /XF *.pyc /XF *.pyi /COPY:DAT  /XO /FFT /DST /TS /NOCLONE /TIMFIX /NJH 

set XCOPY_FILE_ARGS=/D /Y

rem set ONGOING_COPY_ARGS=/E /XD .git /XF *.mpy /COPY:DAT /XO /FFT /DST /TS /MON:1 /NOCLONE /TIMFIX /NJH  %ROBOCOPY_NONVERBOSE%
rem robocopy %CIRCUITPY_IMAGE_PATH% %CIRCUITPY_FLASH_PATH%\lib %ONGOING_COPY_ARGS%  
rem goto :eof

rem robocopy %CIRCUITPY_DEPENDNCIES_PATH% %CIRCUITPY_FLASH_PATH% %ROBOCOPY_ARGS% 

call :copy_image_path_to_lib TerrainTronics
call :copy_image_path_to_lib LumensalisCP
rem call :copy_cp_file code.py

GOTO :eof
set UPDATE_FROM_CIRCUITPY=0
if "x%1" EQU "x-F" set UPDATE_FROM_CIRCUITPY=1

if "x%1" EQU "x1" set ROBOCOPY_ARGS= /MAXAGE:1 %ROBOCOPY_ARGS% 

GOTO :eof

:copy_image_path_to_lib
echo SYNCING  %1 %2 %3 BETWEEN %CIRCUITPY_FLASH_PATH% AND %CIRCUITPY_IMAGE_PATH%



echo ... %CIRCUITPY_IMAGE_PATH% to %CIRCUITPY_FLASH_PATH%\lib
robocopy %CIRCUITPY_IMAGE_PATH%\%1 %CIRCUITPY_FLASH_PATH%\lib\%1 %2 %3 %4 %ROBOCOPY_ARGS% 


exit /B


:copy_cp_file
echo SYNCING  %1 FROM  %CIRCUITPY_IMAGE_PATH% TO %CIRCUITPY_FLASH_PATH%
XCOPY  %CIRCUITPY_IMAGE_PATH%\%1 %CIRCUITPY_FLASH_PATH%\%1 %XCOPY_FILE_ARGS%
echo SYNCING  %1 FROM  %CIRCUITPY_FLASH_PATH% TO %CIRCUITPY_IMAGE_PATH%
XCOPY  %CIRCUITPY_FLASH_PATH%\%1 %CIRCUITPY_IMAGE_PATH%\%1 %XCOPY_FILE_ARGS%

exit /B
