@echo off

set CIRCUITPY_FLASH_PATH=F:
set CIRCUITPY_IMAGE_PATH=.\CircuitPyPartialImage
set ROBOCOPY_NONVERBOSE= /NJH /NJS /NDL
set ROBOCOPY_ARGS=/E /XD .git /COPY:DAT  /XO /FFT /TS /NOCLONE 

set XCOPY_FILE_ARGS=/D /Y

call :copy_cp_path lib\TerrainTronics
call :copy_cp_file code.py


GOTO :eof

:copy_cp_path
echo SYNCING  %1 %2 %3 BETWEEN %CIRCUITPY_FLASH_PATH% AND %CIRCUITPY_IMAGE_PATH%

echo ... %CIRCUITPY_FLASH_PATH% to %CIRCUITPY_IMAGE_PATH%
robocopy %CIRCUITPY_FLASH_PATH%\%1 %CIRCUITPY_IMAGE_PATH%\%1 %2 %3 %4 %ROBOCOPY_ARGS% 

echo ... %CIRCUITPY_IMAGE_PATH% to %CIRCUITPY_FLASH_PATH%
robocopy %CIRCUITPY_IMAGE_PATH%\%1 %CIRCUITPY_FLASH_PATH%\%1 %2 %3 %4 %ROBOCOPY_ARGS% 

exit /B


:copy_cp_file
rem call :copy_cp_path . %1
echo SYNCING  %1 FROM  %CIRCUITPY_IMAGE_PATH% TO %CIRCUITPY_FLASH_PATH%
XCOPY  %CIRCUITPY_IMAGE_PATH%\%1 %CIRCUITPY_FLASH_PATH%\%1 %XCOPY_FILE_ARGS%
echo SYNCING  %1 FROM  %CIRCUITPY_FLASH_PATH% TO %CIRCUITPY_IMAGE_PATH%
XCOPY  %CIRCUITPY_FLASH_PATH%\%1 %CIRCUITPY_IMAGE_PATH%\%1 %XCOPY_FILE_ARGS%

exit /B
